import io
p = r"C:\Users\Josep\AppData\Local\Temp\claude\C--Users-Josep--claude\f2051431-8954-4594-9860-3b743569602a\scratchpad\newweeks\wk23-days.md"
t = io.open(p, encoding="utf-8").read()

R = [
# ---------- DAY 155 (-15) ----------
("Cut six strips of thick card from a cereal box, two fingers wide, and stand the paints and a jar of water beside them. Buy a ripe banana and a candle for tomorrow.",
 "Cut six strips of thick card from a cereal box, two fingers wide, and stand the paints and a jar of water beside them. Buy a ripe banana and a candle."),
("> out of the bag too big to swallow: a leaf the size of your hand, a pebble he\n> cannot close a fist around. At 11 months he passes objects hand to hand and\n> turns them over to check the back. Sit him near the table, where he can pull\n> up on a chair leg.",
 "> out of the bag too big to swallow: a leaf the size of your hand, a pebble he\n> cannot close a fist around. At 11 months he passes objects hand to hand and\n> turns them over to check the back. Sit him near the table, where he can pull\n> up on a chair leg to see."),
("> Good job lands on Azlyn as a verdict. She hears that you approved, has no\n> idea which part you approved of, and the next strip is aimed at collecting the\n> verdict again. Appreciation hands her the detail back: you mixed white in five\n> times before you stopped, or there are three reds here and this morning I\n> could see one. Children given that kind of descriptive feedback stay with hard\n> work longer and hold up better when it goes wrong, because their read on how\n> it went sits in the work rather than your face. Thank her for the board on the\n> wall too.",
 "> Good job lands on Azlyn as a verdict. She hears that you approved, has no\n> idea which part, and the next strip is aimed at collecting the verdict again.\n> Appreciation hands her the detail back: you mixed white in five times before\n> you stopped, or there are three reds here and this morning I could see one.\n> Children given that kind of descriptive feedback stay with hard work longer\n> and hold up better when it goes wrong, because their read on how it went sits\n> in the work rather than your face. Thank her for the board on the wall too."),

# ---------- DAY 156 (-110) ----------
("Leave a spotty banana out on the side and find last June's photos on your phone tonight. Check you have two ice-cube trays and a handful of lolly sticks for tomorrow.",
 "Leave a spotty banana out on the side and find last June's photos on your phone. Check you have two ice-cube trays and a handful of lolly sticks for tomorrow."),
("Take both children out with no shoes on. June grass is dry by ten and still\ncool underneath, and Kreston has spent his first year on carpet, lino and your\nhip. Set him down and watch his feet come straight back up. Plenty of babies\nrefuse grass for weeks. Azlyn's job is to stand a few steps off and be worth\ncrossing it for.",
 "Take both children out with no shoes on. June grass is dry by ten and still\ncool underneath, and Kreston has spent his first year on carpet, lino and your\nhip. Set him down and watch his feet come straight back up. Plenty of babies\nrefuse grass for weeks. Azlyn's job is to stand a few steps off and be worth\nthe crossing."),
("1. Blow the balloons up yourself and let Azlyn bat them round the room while you spread the sheet out flat.\n2. Cake in the middle of the sheet, Kreston in front of it, everyone else down on the floor at his level.\n3. Light the candle, sing, and blow it out yourself after ten seconds. Pull it straight out of the icing and put it up on a high shelf.\n4. Hands off him. He goes in with one finger, then a fist, then his whole face. Azlyn will want to help and the answer is no, this one is his.\n5. Flannel over his face and hands at the end, rinsed in the bowl between passes.\n6. Paint his palm with your finger and press it onto one sheet of paper. Do Azlyn's on the second, and write June and both ages beside the prints.\n7. Both of them at the door frame, mark with the pencil, date and name each line. Then bring up last June's photos and hold the phone against the wall beside his mark.\n\n> \U0001f4a1 **Tip:** Some babies hate it. Kreston may stare at the cake, or object to the texture on his hands. Push one finger in for him, then leave him be, and hand the whole thing to Azlyn if he is still not interested in two minutes.",
 "1. Blow the balloons up yourself and let Azlyn bat them round the room while you spread the sheet flat.\n2. Cake in the middle of it, Kreston in front of the cake, everyone else on the floor at his level.\n3. Light the candle, sing, and blow it out after ten seconds. Pull it out of the icing and put it up on a high shelf.\n4. Hands off him. He goes in with one finger, then a fist, then his face. Azlyn will want to help and the answer is no, this one is his.\n5. Flannel over his face and hands at the end, rinsed in the bowl between passes.\n6. Paint his palm with your finger and press it onto one sheet of paper. Azlyn's on the second, with June and both ages written beside the prints.\n7. Both of them at the door frame, mark with the pencil, date and name each line. Then bring up last June's photos and hold the phone against the wall beside his mark.\n\n> \U0001f4a1 **Tip:** Some babies hate it. Kreston may stare at the cake, or object to the texture. Push one finger in for him, then leave him be, and hand the whole thing to Azlyn if nothing has happened in two minutes."),
("> expected, and afterwards they investigate the object that misbehaved rather\n> than the one that behaved. A ball that hangs in the air gets shaken. A cake he\n> may sit in gets taken apart with both hands. Azlyn gets the same gift from the\n> other side, watching an adult rule suspended on purpose and finding out that\n> rules have reasons and edges.",
 "> expected, and afterwards they investigate the object that misbehaved rather\n> than the one that behaved. A ball that hangs in the air gets shaken. A cake he\n> may sit in gets taken apart with both hands. Azlyn gets the same gift from the\n> other side, watching a rule suspended on purpose and learning that rules have\n> edges."),
("> \u26a0\ufe0f **Safety:** Balloons are the real one today. Uninflated and burst latex is\n> among the worst choking hazards there is for a child under three, so you\n> inflate them and every burst piece comes up off the floor before Kreston goes\n> back down. The candle is lit for ten seconds and blown out by an adult, then\n> it comes out of the cake and goes up high. No honey for Kreston, no whole\n> grapes, no whole nuts.",
 "> \u26a0\ufe0f **Safety:** Balloons are the real one today. Uninflated and burst latex is\n> among the worst choking hazards there is under three, so you inflate them and\n> every burst piece comes up off the floor before Kreston goes back down. The\n> candle is lit for ten seconds, blown out by an adult, then out of the cake and\n> up high. No honey for Kreston, no whole grapes, no whole nuts."),

# ---------- DAY 157 (-60) ----------
("1. Twist each tray over the metal one and let her push the cubes out from underneath. A few snap off their sticks, and the broken ones stay in.\n2. Sort them into colour piles on the tray and count each pile out loud.\n3. Stand the metal tray on the table out of Kreston's reach, spread the towel by the back door, and go and find your shoes. They are melting already, and that is the clock for the morning.",
 "1. Twist each tray over the metal one and let her push the cubes out from underneath. A few snap off their sticks, and the broken ones stay in.\n2. Sort them into colour piles on the tray and count each pile out loud.\n3. Stand the tray on the table out of Kreston's reach, drop the towel by the back door and go and find your shoes. They are melting already, and that is the clock for the morning."),
("1. Chalk a straight line across the paving and lay two sheets of paper with their top edges against it.\n2. She takes a red cube by the stick and drags it from the line down the paper. It goes on pale, then floods behind itself.\n3. Fresh sheet, same red, same line, same direction. Ask her before she starts whether it will do the same thing twice.\n4. Run all three colours twice, one sheet each, and leave the pairs side by side on the path.\n5. Let her draw straight onto the paving with a cube and watch the sun take the line back inside a few minutes.",
 "1. Chalk a straight line across the paving and lay two sheets of paper with their top edges against it.\n2. She takes a red cube by the stick and drags it from the line down the paper. It goes on pale, then floods behind itself.\n3. Fresh sheet, same red, same line, same direction. Ask her first whether it will do the same thing twice.\n4. Run all three colours twice, one sheet each, and leave the pairs side by side on the path.\n5. Let her draw onto the paving with a cube and watch the sun take the line back inside a few minutes."),
("Walk one street and count greens. Early June carries more of them than any\nother week: new leaf on the hedge, dark holly, the blue-green of a spruce,\ngrass, moss in the wall, a wheelie bin, somebody's front door. Ask her for two\ngreens that are not the same green, then hold the leaf against the bin lid so\nshe can see she was right.",
 "Walk one street and count greens. Early June carries more of them than any\nother week: new leaf on the hedge, dark holly, the blue-green of a spruce,\ngrass, moss in the wall, a wheelie bin, somebody's front door. Ask her for two\ngreens that are not the same green, then hold the leaf against the bin lid."),
("> watched somebody else do. Hand him a corner of the old towel and say wipe, and\n> he pushes it round the step with real intent. Keep him off the wet paving and\n> away from the ice. Sit him in sight of the drying paper so he can watch it\n> change without reaching it.",
 "> watched somebody else do. Hand him a corner of the old towel and say wipe, and\n> he pushes it round the step with real intent. Keep him off the wet paving and\n> away from the ice. Sit him in sight of the drying paper, out of reach of it."),
("> doing what every scientist does before a result counts, checking that the\n> world behaves the same way when nobody changed anything. A three-year-old has\n> no reason to assume it will. Her days are full of one-offs, and the idea that\n> a cause repeats gets built out of cases she watched happen more than once. The\n> second run is also the only thing she can compare the first against, so it is\n> where small differences show up. Say the numbers out loud both times and let\n> her call the match.",
 "> doing what every scientist does before a result counts, checking that the\n> world behaves the same way when nobody changed anything. A three-year-old has\n> no reason to assume it will. Her days are full of one-offs, and the idea that\n> a cause repeats gets built out of cases she watched happen twice. The second\n> run is also the only thing she can compare the first against, so it is where\n> small differences show up. Say the numbers out loud both times and let her\n> call the match."),

# ---------- DAY 158 (-30) ----------
("Stand the kitchen roll, the coffee filters and three cups of food colouring on the baking tray. If you have no dark paper for Tuesday, paint a flattened cereal box black now so it dries overnight.",
 "Stand the kitchen roll, the coffee filters and the food colouring on the baking tray. If you have no dark paper for Tuesday, paint a flattened cereal box black so it dries overnight."),
("Stand under the leafiest tree on the street on a bright June morning and look\ndown. The light through the gaps lands in dozens of small discs, and every one\nis round even though not one gap up there is. Hold a sheet of paper underneath\nso she can see the edges, then move it up and down and watch them grow.",
 "Stand under the leafiest tree on the street on a bright June morning and look\ndown. The light through the gaps lands in dozens of small discs, and every one\nis round even though not one gap up there is. Hold paper underneath so she can\nsee the edges, then move it up and down and watch them grow."),
("> off the floor with a finger and thumb. Give him a dry coffee filter to\n> crumple, open and crumple again, and take it back before it goes in his mouth.\n> Under the tree, lay him on his back and let him look up. Light moving through\n> leaves holds a one-year-old longer than anything you could buy.",
 "> off the floor with a finger and thumb. Give him a dry coffee filter to\n> crumple, open and crumple again, and take it back before it goes in his mouth.\n> Under the tree, lay him on his back. Light moving through leaves holds a\n> one-year-old longer than anything you could buy."),
("> work than a fact she takes at nine in the morning, because she keeps testing\n> it: on the filter, under the tree, in the bath tonight. Children whose\n> questions get turned back to them (what do you think, shall we try it) go on\n> to ask more, and asking outlives every answer you happen to have. Say I do not\n> know out loud. She finds out that adults live with open questions.",
 "> work than a fact she takes at nine in the morning, because she keeps testing\n> it: on the filter, under the tree, in the bath tonight. Children whose\n> questions get turned back to them (what do you think, shall we try it) ask\n> more of them, and asking outlives every answer you have. Say I do not know out\n> loud. She finds out that adults live with open questions."),

# ---------- DAY 159 (-77) ----------
("Check the two dark sheets are dry and stand them by the back door with a handful of stones. Pack the swim bags tonight, and buy a red cabbage while you are out today.",
 "Check the dark sheets are dry and stand them by the back door with a handful of stones. Pack the swim bags, and buy a red cabbage while you are out today."),
("1. Walk her round the house hunting for six things that lie flat. Keys, a fork, a comb, a lolly stick, two leaves off the garden.\n2. Test each by laying it on the dark sheet and looking sideways for a gap of light underneath. Anything that rocks goes back.\n3. Load the six into the tray and carry it out. She picks the sunniest spot and you go with her choice.",
 "1. Walk her round the house hunting for six things that lie flat. Keys, a fork, a comb, a lolly stick, two leaves off the garden.\n2. Test each on the dark sheet, looking sideways for a gap of light underneath. Anything that rocks goes back.\n3. Load the six into the tray and carry it out. She picks the sunniest spot and you go with her choice."),
("1. She cuts a shape out of a paper scrap with the child scissors. Whatever comes out is the sixth object.\n2. Lay one dark sheet flat in the spot she chose and let her arrange all six on it, spaced so nothing overlaps.\n3. Weight the corners with stones, and lay a peg along any edge that lifts.\n4. Write the time in marker on the corner of the sheet, then photograph it from above.\n5. The second sheet goes indoors on a shelf away from every window, bare, with the same time on it. That one is the comparison and it does nothing all day.\n6. Leave both until 1:00. She will want to look, so agree now that the looking happens after lunch.\n\n> \U0001f4a1 **Tip:** Choose the spot for where the sun will be at noon rather than half nine. A sheet in shade by eleven gives you nothing to hold up this afternoon.",
 "1. She cuts a shape out of a paper scrap with the child scissors. Whatever comes out is the sixth object.\n2. Lay one dark sheet flat in the spot she chose and let her arrange all six on it, spaced so nothing overlaps.\n3. Weight the corners with stones, and lay a peg along any edge that lifts.\n4. Write the time in marker on the corner of the sheet and photograph it from above.\n5. The second sheet goes indoors on a shelf away from every window, bare, same time on it. That one is the comparison and it does nothing all day.\n6. Leave both until 1:00, and agree now that the looking happens after lunch.\n\n> \U0001f4a1 **Tip:** Choose the spot for where the sun will be at noon rather than half nine. A sheet in shade by eleven gives you nothing to hold up later."),
("Walk the street hunting for what the sun has already bleached. A red slide gone\npink, an estate agent's board faded in a window, a car roof duller than its\ndoors, dry yellow grass on the sunny verge and green on the shaded one. Put her\nhand flat on a dark car bonnet and then a white one, and let her tell you which\ncolour the sun prefers.",
 "Walk the street hunting for what the sun has already bleached. A red slide gone\npink, an estate agent's board faded in a window, dry yellow grass on the sunny\nverge and green on the shaded one. Put her hand flat on a dark car bonnet and\nthen a white one, and let her tell you which colour the sun prefers."),
("> June sun on his own feet. Hat, shade and cream before he goes out. He will\n> make straight for the stones, so keep the sheet at the far end of the garden\n> and give him a cup and a fistful of cut grass on the shady side. At a year he\n> moves something from one container to another twenty times over.",
 "> June sun on his own feet. Hat, shade and cream before he goes out. He will\n> make straight for the stones, so keep the sheet at the far end of the garden\n> and give him a cup and a fistful of cut grass in the shade. At a year he moves\n> something from one container to another twenty times over."),
("1. Go out together and take the stones off first. She lifts each object herself, one at a time, and you both stop after the first to look.\n2. Carry both sheets to the table and lay the indoor one on top of the sun sheet, edge to edge.\n3. Slide them apart a hand's width so both faces show. The difference reads at the seam better than anywhere else.",
 "1. Go out together and take the stones off first. She lifts each object herself, one at a time, and you both stop after the first to look.\n2. Carry both sheets in and lay the indoor one on top of the sun sheet, edge to edge.\n3. Slide them apart a hand's width. The difference reads at the seam better than anywhere else."),
("> difference at the seam, and she cannot see the thing that caused it, because\n> the cause was four hours going by. Time as a cause is hard at three. Her\n> working model of why anything happens runs on contact: you push it, it moves.\n> Something that changes while nobody touched it needs another sort of\n> explanation, and she builds that out of days like this one, where the only\n> difference between two sheets is how long each sat there. The indoor sheet\n> argues it for you, and she checks that one herself.",
 "> difference at the seam, and she cannot see the thing that caused it, because\n> the cause was four hours going by. Time as a cause is hard at three. Her\n> working model of why anything happens runs on contact: you push it, it moves.\n> Something that changes while nobody touched it needs another sort of\n> explanation, and she builds that out of days like this one, where the only\n> difference between two sheets is how long each sat there. The indoor sheet\n> argues it for you."),

# ---------- DAY 160 (-60) ----------
("Chop half a red cabbage, cover it with boiling water in a bowl and leave it on the side overnight. It goes deep purple by morning, and the smell is the price of admission.",
 "Chop half a red cabbage, cover it with boiling water in a bowl and leave it overnight. It goes deep purple by morning, and the smell is the price of admission."),
("1. Hold the sieve over the jug and let her pour the bowl through it. The cabbage stays behind and the colour goes through.\n2. Hold the jug against the window. It reads purple in the light and near black on the table, and she will say so before you do.\n3. Stand the jug at her place and tell her this water changes colour six times before lunch. Do not say how.",
 "1. Hold the sieve over the jug and let her pour the bowl through it. The cabbage stays behind and the colour goes through.\n2. Hold the jug against the window. It reads purple in the light and near black on the table, and she will say so first.\n3. Stand the jug at her place and tell her this water changes colour six times before lunch. Do not say how."),
("1. Six cups on the tray, each a third full from the jug. Cup one gets nothing all morning and stays where she can see it.\n2. Before anything goes in, hold up the lemon juice and ask what colour it will make. Write her guess down in her words.\n3. Two teaspoons of lemon juice into cup two. Write what happened beside the guess and read her both.\n4. Same again for the vinegar, then a teaspoon of bicarbonate of soda, then a squirt of washing-up liquid, then the fizzy water. Guess first every time, clean teaspoon each time.\n5. Pour the pink cup into the green cup and let her call what is coming before it lands.\n6. Line all six along the windowsill next to cup one and read the guesses back from the top.\n\n> \U0001f4a1 **Tip:** Write the wrong guesses down in the same hand as the right ones. She will notice if you skip one, and the sheet is worth nothing to her the moment it holds only the hits.",
 "1. Six cups on the tray, each a third full from the jug. Cup one gets nothing all morning and stays where she can see it.\n2. Before anything goes in, hold up the lemon juice and ask what colour it will make. Write her guess down in her words.\n3. Two teaspoons of lemon juice into cup two. Write what happened beside the guess and read her both.\n4. Same for the vinegar, then a teaspoon of bicarbonate of soda, a squirt of washing-up liquid, then fizzy water. Guess first every time, clean teaspoon each time.\n5. Pour the pink cup into the green cup and let her call what is coming before it lands.\n6. Line all six along the windowsill beside cup one and read the guesses back from the top.\n\n> \U0001f4a1 **Tip:** Write the wrong guesses in the same hand as the right ones. She will notice if you skip one, and the sheet is worth nothing to her the moment it holds only the hits."),
("June is the purple month around here and she needs six. Lavender by a front\nstep, allium heads gone to seed, clover in the verge, a sticker on a bin,\nsomebody's front door, a blackcurrant. Photograph each so all six come home.\nAsk which is closest to the jug on the kitchen table, and let her argue for one\nyou would not have chosen.",
 "June is the purple month around here and she needs six. Lavender by a front\nstep, allium heads gone to seed, clover in the verge, a sticker on a bin,\nsomebody's front door, a blackcurrant. Photograph each so all six come home,\nask which is closest to the jug on the kitchen table, and let her argue for one\nyou would not have picked."),
("> \U0001f476 **Kreston's Afternoon:** At the library he goes in the board-book corner\n> and chews whatever he finds, which is what board books are built for. At\n> twelve months he carries a book over and drops it in your lap, and that is a\n> request. Read it three times. Let Azlyn choose his one and carry it to the\n> desk herself.",
 "> \U0001f476 **Kreston's Afternoon:** At the library he goes in the board-book corner\n> and chews what he finds, which is what board books are built for. At twelve\n> months he carries a book over and drops it in your lap, and that is a request.\n> Read it three times. Azlyn chooses his and carries it to the desk."),
("> Azlyn said green, the cup went pink, and you wrote both down in the same pen.\n> Nothing bad happened to her. Cabbage water is the cheapest place she will ever\n> be wrong, and the cost of being wrong is what she is learning this morning,\n> well ahead of the chemistry. Children whose predictions get recorded and\n> checked by an adult who stays neutral about the outcome carry on guessing out\n> loud. Children who get corrected go quiet and wait to be told. Read the wrong\n> guesses back in the voice you use for the right ones, and she will still be\n> guessing out loud at eleven, when it counts for more.",
 "> Azlyn said green, the cup went pink, and you wrote both down in the same pen.\n> Nothing bad happened to her. Cabbage water is the cheapest place she will ever\n> be wrong, and the cost of being wrong is what she is learning this morning,\n> well ahead of the chemistry. Children whose predictions get recorded and\n> checked by an adult who stays neutral about the outcome carry on guessing out\n> loud. The corrected ones go quiet and wait to be told. Read the wrong guesses\n> back in the voice you use for the right ones, and she will still be guessing\n> at eleven, when it counts for more."),

# ---------- DAY 161 (-70) ----------
("Stack coloured paper, tissue and old magazine pages on the table with the metal tray, and dig the wool jumper out of the back of the wardrobe.",
 "Stack coloured paper, tissue and old magazine pages on the table with the metal tray, and dig the wool jumper out of the wardrobe."),
("1. Fingers only this morning. No scissors, and say so at the start so she stops asking.\n2. She tears, then tears the pieces again, then again. Ask for pieces smaller than her thumbnail and let her carry on past where you would have stopped.\n3. Spread the whole lot in a thin layer across the metal tray and leave it there. Something happens to it at 9:15.",
 "1. Fingers only this morning. No scissors, and say so at the start so she stops asking.\n2. She tears, then tears the pieces again, then again. Ask for pieces smaller than her thumbnail and let her go past where you would have stopped.\n3. Spread the lot in a thin layer across the metal tray and leave it. Something happens to it at 9:15."),
("5. Go hunting with it. Balloon behind her head and her hair follows. Balloon beside a thin stream from the kitchen tap and the water bends over. Balloon near the crisp packet and it slides.\n6. Let her find one more thing in the house that moves. She will try twenty and land one.\n\n> \U0001f4a1 **Tip:** It fails on a humid day. If nothing lifts, take it to the carpet in a warm room with the window shut and rub for a lot longer than feels sensible.",
 "5. Go hunting. Balloon behind her head and her hair follows. Balloon beside a thin stream from the kitchen tap and the water bends over. Balloon near the crisp packet and it slides.\n6. Let her find one more thing in the house that moves. She will try twenty and land one.\n\n> \U0001f4a1 **Tip:** It fails on a humid day. If nothing lifts, take it to the carpet in a warm room with the window shut and rub for longer than feels sensible."),
("Take one length of ribbon out and hold it up in six places: the front step, the\ncorner, the open end of the street, behind the hedge, under the trees, out in\nthe middle of the green. It hangs dead in some spots and streams in others, and\nthe street she walks every day turns out to have weather along it. Let her call\nthe windiest spot before you get there.",
 "Take one length of ribbon out and hold it up in six places: the front step, the\ncorner, the open end of the street, behind the hedge, under the trees, out in\nthe middle of the green. It hangs dead in some spots and streams in others, and\nthe street she walks every day turns out to have weather along it. Let her call\nthe windiest before you get there."),
("> balloons, so give him the wool jumper on the floor and let him haul it about.\n> At a year he pulls, drags and carries things while he walks, and a jumper is\n> heavy enough to be worth it. Outside, hand him one end of the ribbon, keep\n> hold of the other, and walk backwards.",
 "> balloons, so give him the wool jumper on the floor and let him haul it about.\n> At a year he pulls, drags and carries things while he walks, and a jumper is\n> heavy enough to be worth it. Outside, hand him one end of the ribbon and keep\n> hold of the other."),
("1. Cut the carrier bags into long strips a hand's width across. You cut, she says how long each one gets to be.\n2. Tie the string high between the fence post and the stick pushed into the border, above the reach of anyone small. Or peg the strips to the washing line and leave the string in the drawer.\n3. She pegs the strips along it, spaced out, in whatever order she likes.\n4. Both of you stand back and watch. They all point the same way, and that way is the wind.\n5. Draw an arrow on the fence post with the marker showing where they point, and write the time beside it.\n6. Move one strip to the stillest corner she found this morning and compare it against the line.\n7. Check the arrow after dinner. It will have moved or it will not, and either answer is worth having.\n\n> \U0001f4a1 **Tip:** Tie it high and step back. Half of this is standing still looking at something you set up, and she will do that for as long as you do it first.",
 "1. Cut the carrier bags into long strips a hand's width across. You cut, she says how long each one gets to be.\n2. Tie the string high between the fence post and the stick pushed into the border, above the reach of anyone small. Or peg the strips to the washing line and leave the string in the drawer.\n3. She pegs the strips along it, spaced out, in whatever order she likes.\n4. Both of you stand back. They all point the same way, and that way is the wind.\n5. Draw an arrow on the fence post with the marker showing where they point, and write the time beside it.\n6. Move one strip to the stillest corner she found this morning and compare it against the line.\n7. Check the arrow after dinner. It will have moved or it will not, and either answer is worth having.\n\n> \U0001f4a1 **Tip:** Tie it high and step back. Half of this is standing still looking at something you set up, and she does that for as long as you do it first."),
("> Everything Azlyn has worked out about why things move runs through contact. A\n> hand pushes, a foot kicks, wind arrives on her face. A balloon that lifts\n> paper without touching it breaks that rule, and the real answer sits years\n> past three. What she can take today is the pattern: something happened here,\n> and the cause was not touching. She meets the same idea again in magnets, in\n> the sun fading her paper yesterday, and one day in gravity. Give her the word\n> and leave the mechanism alone. Naming a thing she cannot see is the first\n> handhold, and the explanation can wait.",
 "> Everything Azlyn has worked out about why things move runs through contact. A\n> hand pushes, a foot kicks, wind arrives on her face. A balloon that lifts\n> paper without touching it breaks that rule, and the real answer sits years\n> past three. What she can take today is the pattern: something happened here,\n> and the cause was not touching. She meets the idea again in magnets, in the\n> sun fading her paper yesterday, and one day in gravity. Give her the word and\n> leave the mechanism alone. Naming a thing she cannot see is the first\n> handhold."),
]

for old, new in R:
    n = t.count(old)
    assert n == 1, "count=%d for: %r" % (n, old[:70])
    t = t.replace(old, new)

io.open(p, "w", encoding="utf-8", newline="\n").write(t)
print("ok", len(R))
